# This docker-compose file orchestrates the startup of the entire STAC-Atlas project.
# It includes the docker-compose configurations from the individual components.

#TODO: add docker-compose files for UI and Crawler components

networks:
  stac-network:
    name: stac-network
    external: true

volumes:
  stac_data:

services:
  db:
    extends:
      file: db/docker-compose.yml
      service: database
    networks: [stac-network]

  crawler:
    extends:
      file: crawler/docker-compose.yml
      service: crawler
    networks: [stac-network]
  api:
    extends:
      file: api/docker-compose.yml
      service: api
    networks: [stac-network]

  ui:
    extends:
      file: ui/docker-compose.yml
      service: ui
    networks: [stac-network]