services:
  database:
    image: postgis/postgis:16-3.4
    container_name: stac_db
    restart: always

    environment:
      POSTGRES_DB: stac_db
      POSTGRES_USER: stac_user
      POSTGRES_PASSWORD: stac_password

    ports:
      - "5432:5432"

    volumes:
      - stac_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - stac-network

volumes:
  stac_data:

networks:
  stac-network:
    name: stac-network